name: Deploy Apigee Proxies with Access Token

on:
  push:
    branches:
      - main

jobs:
  deploy-apigee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
          gcloud --version

      - name: Create service account key file
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > creds.json

             
      - name: Verify service account key
        run: |
          cat creds.json

      - name: Activate service account
        env:
          ACCESS_TOKEN: ${{ secrets.GCP_CREDENTIALS }}
        run: |
         echo "$ACCESS_TOKEN" > /tmp/access_token.b64
         base64 --decode /tmp/access_token.b64 > /tmp/creds.json         
         gcloud auth activate-service-account --key-file=/tmp/creds.json
        
      - name: Get Access Token
        id: get_access_token
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo "::set-output name=access_token::$ACCESS_TOKEN"

      - name: Set up apigeecli
        run: |
          sudo apt-get update
          sudo apt-get install unzip
          wget https://github.com/apigee/apigeecli/releases/latest/download/apigeecli_v2.4.3_Linux_x86_64.zip
          ls
          unzip apigeecli_v2.4.3_Linux_x86_64.zip
          find . -name "apigeecli"
          sudo mv ./apigeecli_v2.4.3_Linux_x86_64/apigeecli /usr/local/bin/
          sudo chmod +x /usr/local/bin/apigeecli
          apigeecli --version

      - name: Deploy API Proxy with ApigeeCLI using Access Token
        run: |
          apigeecli apis create bundle --org ${{ secrets.APIGEE_ORG }} --env ${{ secrets.APIGEE_ENV }} --bundle ./apiproxy --name MyProxy --token ${{ steps.get_access_token.outputs.access_token }}
