
name: proxy-deploy

on: #Triggers
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/apigee-proxy-deploy.yaml'
      - 'src/**'

jobs: #definitions
  build:
    name: "Deploy To Dev"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout   #Checkout the Repository
        uses: actions/checkout@v4

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          project_id: 'vital-scout-430808-k8'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          //workload_identity_provider: 'projects/1039037619425/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc'
          //service_account: 'github-actions-workflow@vital-scout-430808-k8.iam.gserviceaccount.com'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK         #Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: Create API bundle          #Create API Proxy Bundle
        run: zip -r proxy.zip apiproxy
      - name: Upload API Proxy Bundle      #Upload API Proxy Bundle
        id: upload
        run: "echo \"::set-output name=apigee-revision::$(curl --fail -X POST -H \"Content-Type: multipart/form-data\" -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" -F \"file=@proxy.zip\" \"https://apigee.googleapis.com/v1/organizations/${{secrets.APIGEE_ORG}}/apis?action=import&name=hello-world-test\" --silent | jq --raw-output .revision)\""
      - name: Deploy Revision    #Deploy API Proxy Revision
        run: "curl --fail -X POST -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" \"https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/environments/dev/apis/hello-world-test/revisions/${{steps.upload.outputs.apigee-revision}}/deployments?override=true\""
  
