name: Deploy Apigee Proxies

on:
  push:
    branches:
      - main

jobs:
  deploy-apigee:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up apigeecli
        run: |
          wget https://github.com/apigee/apigeecli/releases/download/v1.1.5/apigeecli_Linux_x86_64.tar.gz
          tar -xvzf apigeecli_Linux_x86_64.tar.gz
          sudo mv apigeecli /usr/local/bin/

      - name: Authenticate with Apigee
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > creds.json
          apigeecli auth login --service-account creds.json
        env:
          APIGEE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy API Proxy
        run: |
          apigeecli apis create bundle --org ${{ secrets.APIGEE_ORG }} --env ${{ secrets.APIGEE_ENV }} --bundle ./apiproxy --name hello-world-test --wait

      - name: Deploy new revision
        run: |
          REV=$(apigeecli apis latestrev --name hello-world-test --org ${{ secrets.APIGEE_ORG }})
          apigeecli apis deploy --org ${{ secrets.APIGEE_ORG }} --env ${{ secrets.APIGEE_ENV }} --name hello-world-test --rev $REV --wait
