
name: proxy-deploy

on: #Triggers
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/apigee-proxy-deploy.yaml'
      - 'src/**'

jobs: #definitions
  build:
    name: "Deploy To Dev"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout   #Checkout the Repository
        uses: actions/checkout@v4

  # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id:  'vital-scout-430808-k8'
          export_default_credentials: true
      - name: Create API bundle          #Create API Proxy Bundle
        run: zip -r proxy.zip apiproxy
      - name: Upload API Proxy Bundle      #Upload API Proxy Bundle
        id: upload
        run: "echo \"::set-output name=apigee-revision::$(curl --fail -X POST -H \"Content-Type: multipart/form-data\" -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" -F \"file=@proxy.zip\" \"https://apigee.googleapis.com/v1/organizations/${{secrets.APIGEE_ORG}}/apis?action=import&name=hello-world-test\" --silent | jq --raw-output .revision)\""
      - name: Deploy Revision    #Deploy API Proxy Revision
        run: "curl --fail -X POST -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" \"https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/environments/dev/apis/hello-world-test/revisions/${{steps.upload.outputs.apigee-revision}}/deployments?override=true\""
  
