name: Deploy Apigee Proxies

on:
  push:
    branches:
      - main

jobs:
  deploy-apigee:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up apigeecli
        run: |
          sudo apt-get update
          sudo apt-get install unzip
          wget https://github.com/apigee/apigeecli/releases/latest/download/apigeecli_v2.4.3_Linux_x86_64.zip
          ls
          unzip apigeecli_v2.4.3_Linux_x86_64.zip
          find . -name "apigeecli"
          sudo mv ./apigeecli_v2.4.3_Linux_x86_64/apigeecli /usr/local/bin/
          sudo chmod +x /usr/local/bin/apigeecli
          apigeecli --version


      - name: Set up Apigee credentials
        env:
          APIGEE_CREDS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$APIGEE_CREDS" > apigee_sa_key.json

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Generate access token
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo "ACCESS_TOKEN=$GCP_CREDENTIALS" >> $GITHUB_ENV

      - name: Use apigeecli with token
        run: |
          apigeecli apis list -o ${{ secrets.APIGEE_ORG }} -t $ACCESS_TOKEN
        

      - name: Deploy API Proxy
        run: |
          apigeecli apis create bundle --org ${{ secrets.APIGEE_ORG }} --env ${{ secrets.APIGEE_ENV }} --bundle ./apiproxy --name hello-world-test --wait

      - name: Deploy new revision
        run: |
          REV=$(apigeecli apis latestrev --name hello-world-test --org ${{ secrets.APIGEE_ORG }})
          apigeecli apis deploy --org ${{ secrets.APIGEE_ORG }} --env ${{ secrets.APIGEE_ENV }} --name hello-world-test --rev $REV --wait
