name: Deploy Apigee Proxies with Access Token

on:
  push:
    branches:
      - main

jobs:
  deploy-apigee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up apigeecli
        run: |
          sudo apt-get update
          sudo apt-get install unzip
          wget https://github.com/apigee/apigeecli/releases/latest/download/apigeecli_v2.4.3_Linux_x86_64.zip
          ls
          unzip apigeecli_v2.4.3_Linux_x86_64.zip
          find . -name "apigeecli"
          sudo mv ./apigeecli_v2.4.3_Linux_x86_64/apigeecli /usr/local/bin/
          sudo chmod +x /usr/local/bin/apigeecli
          apigeecli --version

      - name: Set up Google Cloud SDK
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
          gcloud --version

      - name: Create service account key file
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > creds.json

             
      - name: Verify service account key
        run: |
          cat creds.json
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
           credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
          

      - name: Deploy API Proxy with ApigeeCLI using Access Token
        run: |
          apigeecli apis deploy --org ${{ secrets.APIGEE_ORG }} --env ${{ secrets.APIGEE_ENV }} --name hello-world-test --rev 2 --token ${{ steps.get_access_token.outputs.access_token }}
