name: Reusable Apigee Proxy Deployment

on:
  workflow_call:
    inputs:
      proxy_name:
        description: The name of the API proxy to deploy
        required: true
        type: string
      proxy_directory:
        description: Working directory to zip up as your proxy bundle
        required: false
        type: string
        default: 'apiproxy'
      dev_env:
        description: The name of the development environment
        required: true
        type: string
      test_env:
        description: The name of the testing environment
        required: true
        type: string
      uat_env:
        description: The name of the UAT environment
        required: true
        type: string
      runner:
        description: The runner to use for the job
        required: false
        default: 'ubuntu-latest'
        type: string
      repository:
        description: 'The repository to checkout'
        required: false
        type: string
        default: ${{ github.repository }}
    secrets:
      apigee_org:
        required: true
      service_account:
        required: true
      workload_identity_provider:
        required: true

jobs:
  Deploy_Apigee_Proxy:
    name: "Deploy API"
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      id-token: write
    env:
      APIGEE_ORG: ${{ secrets.apigee_org }}
      APIGEE_PROXY_NAME: ${{ inputs.proxy_name }}
      APIGEE_DEV_ENV: ${{ inputs.dev_env }}
      APIGEE_TEST_ENV: ${{ inputs.test_env }}
      APIGEE_UAT_ENV: ${{ inputs.uat_env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install apigeelint
        run: npm install -g apigeelint@2.16.0

      - name: Run apigeelint
        run: |
          echo "Starting apigeelint analysis..."
          apigeelint -s ${{ inputs.proxy_directory }} -f json.js --maxWarnings 10 > linting-results.json

          ERRORS=$(jq '[.[] | select(.severity == "Error")] | length' linting-results.json)
          WARNINGS=$(jq '[.[] | select(.severity == "Warning")] | length' linting-results.json)

          echo "Linting Complete: Errors - $ERRORS, Warnings - $WARNINGS"
          if [ $ERRORS -gt 0 ]; then
            echo "Linting errors found. Check the detailed results."
            exit 1
          fi

      - name: Save detailed linting results
        uses: actions/upload-artifact@v3
        with:
          name: detailed-linting-results
          path: linting-results.json

      - name: Delete Older Revisions (Keep Last 3)
        run: |
          echo "Deleting older revisions, keeping the last 3..."
          sudo apt-get install -y jq

          ACCESS_TOKEN=$(gcloud auth application-default print-access-token)

          revisions=$(curl -s -X GET -H "Authorization: Bearer $ACCESS_TOKEN" \
            "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/apis/$APIGEE_PROXY_NAME/revisions" \
            | jq -r '.revisions[]' | sort -n)

          revision_count=$(echo "$revisions" | wc -l)

          if [ "$revision_count" -le 3 ]; then
            echo "Only $revision_count revisions found. No need to delete any revisions."
          else
            current_revision=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" \
              "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_DEV_ENV/deployments" | \
              jq -r --arg PROXY "$APIGEE_PROXY_NAME" '.deployments[] | select(.apiProxy == $PROXY) | .revision')

            revisions_to_delete=$(echo "$revisions" | grep -v -F "$current_revision" | head -n -3)

            for rev in $revisions_to_delete; do
              echo "Deleting revision $rev of proxy $APIGEE_PROXY_NAME"
              delete_response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: Bearer $ACCESS_TOKEN" \
                "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/apis/$APIGEE_PROXY_NAME/revisions/$rev")

              if [ "$delete_response" -eq 200 ]; then
                echo "Revision $rev deleted successfully."
              else
                echo "Failed to delete revision $rev. HTTP status code: $delete_response"
              fi
            done
          fi

      - name: Upload API Proxy Bundle
        id: upload
        run: |
          ACCESS_TOKEN=$(gcloud auth application-default print-access-token)
          response=$(curl --fail -X POST \
            -H "Content-Type: multipart/form-data" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -F "file=@proxy.zip" \
            "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/apis?action=import&name=$APIGEE_PROXY_NAME" \
            --silent)

          revision=$(echo "$response" | jq --raw-output .revision)
          echo "Uploaded Proxy Revision: $revision"
          echo "apigee-revision=$revision" >> $GITHUB_OUTPUT

      - name: Deploy and Validate in Dev Environment
        id: deploy
        run: |
          echo "Deploying to Development Environment: ${{ inputs.dev_env }}"
          curl -X POST \
            -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
            "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_DEV_ENV/apis/$APIGEE_PROXY_NAME/revisions/${{ steps.upload.outputs.apigee-revision }}/deployments?override=true"

      - name: Generate Deployment Summary
        run: |
          echo -e "\n## Deployment Version Information"
          echo "| Proxy Name | Old Version | New Version | Status |"
          echo "|------------|-------------|-------------|--------|"
          echo "| ${{ inputs.proxy_name }} | ${{ steps.upload.outputs.current-revision }} | ${{ steps.upload.outputs.apigee-revision }} | READY |"
