name: Reusable Apigee Proxy Deployment

on:
  workflow_call:
    inputs:
      proxy_name:
        description: The name of the API proxy to deploy
        required: true
        type: 'string'
      proxy_directory:
        description: Working directory to zip up as your proxy bundle
        required: false
        type: 'string'
        default: 'apiproxy'
      dev_env:
        description: The name of the development environment
        required: true
        type: 'string'
      test_env:
        description: The name of the testing environment
        required: true
        type: 'string'
      uat_env:
        description: The name of the UAT environment
        required: true
        type: 'string'
      runner:
        description: The runner to use for the job
        required: false
        default: 'ubuntu-latest'
        type: 'string'
      repository:
        description: 'The repository to checkout'
        required: false
        type: 'string'
        default: ${{ github.repository }}
    secrets:
      apigee_org:
        required: true
      service_account:
        required: true
      workload_identity_provider:
        required: true

jobs:
  Deploy_Apigee_Proxy:
    name: "Deploy API"
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      id-token: write
    env:
      APIGEE_ORG: ${{ secrets.apigee_org }}
      APIGEE_PROXY_NAME: ${{ inputs.proxy_name }}
      APIGEE_DEV_ENV: ${{ inputs.dev_env }}
      APIGEE_TEST_ENV: ${{ inputs.test_env }}
      APIGEE_UAT_ENV: ${{ inputs.uat_env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install apigeelint
        run: npm install -g apigeelint@2.16.0

      - name: Run apigeelint
        run: |
          echo "Starting apigeelint analysis..."
          echo "Analyzing proxy in directory: ${{ inputs.proxy_directory }}"
          apigeelint -s ${{ inputs.proxy_directory }} -f json.js --maxWarnings 10 > linting-results.json
          echo "Apigeelint analysis complete. Results saved to linting-results.json"
          
          # Display detailed linting results
          echo "Detailed Linting Results:"
          jq -r '.[] | "Rule: \(.ruleId)\nSeverity: \(.severity)\nMessage: \(.message)\nFile: \(.filePath)\nLine: \(.lineNumber)\n"' linting-results.json
          
          # Count errors and warnings
          ERRORS=$(jq '[.[] | select(.severity == "Error")] | length' linting-results.json)
          WARNINGS=$(jq '[.[] | select(.severity == "Warning")] | length' linting-results.json)
          
          echo "Summary of results:"
          echo "Errors: $ERRORS"
          echo "Warnings: $WARNINGS"
          
          if [ $ERRORS -gt 0 ]; then
            echo "Linting errors found. Check the detailed results above."
            exit 1
          fi

      - name: Save detailed linting results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: detailed-linting-results
          path: linting-results.json

      - name: Check proxy directory contents
        run: ls -la ${{ inputs.proxy_directory }}

      - name: Create API bundle
        run: zip -r proxy.zip ${{ inputs.proxy_directory }}

      - name: Authenticate to GCP
        id: auth
        run: |
          ACCESS_TOKEN=$(gcloud auth application-default print-access-token)
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      - name: Upload API Proxy Bundle
        id: upload
        env:
          ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
          APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
        run: |
          response=$(curl --fail -X POST \
            -H "Content-Type: multipart/form-data" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -F "file=@proxy.zip" \
            "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/apis?action=import&name=$APIGEE_PROXY_NAME" \
            --silent)

          echo "Apigee Response: $response"

          revision=$(echo "$response" | jq --raw-output .revision)
          echo "apigee-revision=$revision" >> $GITHUB_OUTPUT

      - name: Deploy to Dev Environment and Validate Revision
        env:
          APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
          APIGEE_ENV: ${{ inputs.dev_env }}
          APIGEE_PROXY_NAME: ${{ inputs.proxy_name }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
          "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_ENV/apis/$APIGEE_PROXY_NAME/revisions/${{ steps.upload.outputs.apigee-revision }}/deployments?override=true"

          echo "Waiting for deployment to complete..."
          sleep 60

          max_retries=5
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
            VALIDATION_OUTPUT=$(curl -s -X GET \
              -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
              "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_ENV/apis/$APIGEE_PROXY_NAME/revisions/${{ steps.upload.outputs.apigee-revision }}/deployments")
            
            echo "Validation Output: $VALIDATION_OUTPUT"
            
            if echo "$VALIDATION_OUTPUT" | jq -e '.state == "READY"' > /dev/null; then
              echo "Deployment validated successfully!"
              exit 0
            elif echo "$VALIDATION_OUTPUT" | jq -e '.state == "PROGRESSING"' > /dev/null; then
              echo "Deployment still in progress. Retrying..."
              sleep 30
              retry_count=$((retry_count+1))
            else
              echo "Deployment failed or in unexpected state!"
              exit 1
            fi
          done

          echo "Deployment validation failed after $max_retries retries!"
          exit 1

      - name: Validate Deployment State in Dev Environment
        env:
          APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
          APIGEE_DEV_ENV: ${{ inputs.dev_env }}
          APIGEE_PROXY_NAME: ${{ inputs.proxy_name }}
          ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
        run: |
          VALIDATION_OUTPUT=$(curl -s -X GET \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            "https://apigee.googleapis.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_DEV_ENV/apis/$APIGEE_PROXY_NAME/revisions/${{ steps.upload.outputs.apigee-revision }}/deployments")

          echo "Validation Output: $VALIDATION_OUTPUT"

          if echo "$VALIDATION_OUTPUT" | grep -q '"state": "READY"'; then
            echo "Deployment state validated successfully!"
          else
            echo "Deployment validation failed!"
            exit 1
          fi
      - name: Generate Summary Table
        if: always()
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Step | Status | Details |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|---------|" >> $GITHUB_STEP_SUMMARY
          echo "| Linting | $([ $(jq '[.[] | select(.severity == "Error")] | length' linting-results.json) -eq 0 ] && echo '✅ Pass' || echo '❌ Fail') | Errors: $(jq '[.[] | select(.severity == "Error")] | length' linting-results.json), Warnings: $(jq '[.[] | select(.severity == "Warning")] | length' linting-results.json) |" >> $GITHUB_STEP_SUMMARY
          echo "| API Bundle Upload | ✅ Success | Revision: ${{ steps.upload.outputs.apigee-revision }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Deployment to Dev | $(echo '${{ steps.upload.outputs.apigee-revision }}' | jq -r '.state // "N/A"') | Environment: ${{ inputs.dev_env }} |" >> $GITHUB_STEP_SUMMARY
          
          echo "## Detailed Linting Results" >> $GITHUB_STEP_SUMMARY
          echo "| Rule ID | Severity | Message | File | Line |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|----------|---------|------|------|" >> $GITHUB_STEP_SUMMARY
          jq -r '.[] | "| \(.ruleId) | \(.severity) | \(.message) | \(.filePath) | \(.lineNumber) |"' linting-results.json >> $GITHUB_STEP_SUMMARY

      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Apigee Proxy Deployment Summary - ${{ inputs.proxy_name }}
          body: file://README.md
          to: happyanand06@gmail.com
          from: GitHub Actions
          content_type: text/html
          convert_markdown: true

      - name: Prepare Email Content
        if: always()
        run: |
          echo "## Deployment Summary" > README.md
          echo "| Step | Status | Details |" >> README.md
          echo "|------|--------|---------|" >> README.md
          echo "| Linting | $([ $(jq '[.[] | select(.severity == "Error")] | length' linting-results.json) -eq 0 ] && echo '✅ Pass' || echo '❌ Fail') | Errors: $(jq '[.[] | select(.severity == "Error")] | length' linting-results.json), Warnings: $(jq '[.[] | select(.severity == "Warning")] | length' linting-results.json) |" >> README.md
          echo "| API Bundle Upload | ✅ Success | Revision: ${{ steps.upload.outputs.apigee-revision }} |" >> README.md
          echo "| Deployment to Dev | $(echo '${{ steps.upload.outputs.apigee-revision }}' | jq -r '.state // "N/A"') | Environment: ${{ inputs.dev_env }} |" >> README.md
          
          echo "## Detailed Linting Results" >> README.md
          echo "| Rule ID | Severity | Message | File | Line |" >> README.md
          echo "|---------|----------|---------|------|------|" >> README.md
          jq -r '.[] | "| \(.ruleId) | \(.severity) | \(.message) | \(.filePath) | \(.lineNumber) |"' linting-results.json >> README.md
